### PR TITLE
Fix: Illuminate\Support's modified ArrayableInterface

### LINKED ISSUE #36: Update Deprecated/Modified Illuminate/Support Interface Usage
Heads-up everyone! 

While working with the package, we've noticed that it's using the deprecated `ArrayableInterface` from the old Illuminate\Support\Contracts namespace. This interface has been modified and relocated under Illuminate\Contracts\Support, now named simply `Arrayable`.

### PR DESCRIPTION
**Pull request by erkinboy-botirov**
fixes #36

### CODE REVIEW

**Comment by BilalAslim** [comment]
@erkinboy-botirov  Thank you for your contribution, can you please merge in master so that the workflow and automated tests can run? I have had to reenable the workflow due to inactivity.

**Comment by erkinboy-botirov** [comment]
@BilalAslim, master has been merged in.

**Comment by BilalAslim** [comment]
@erkinboy-botirov Thank you for your help with the project. Uzbekistan has very good food and tea!

**Comment by erkinboy-botirov** [comment]
It's been a pleasure contributing. And yes, food culture here is indeed amazing. Glad you liked it.

**Pull request merged**
