### PR TITLE
PHP 8.1 Support

### LINKED ISSUE #25: Add php 8.1 support
Currently experience this error:

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Request.php:637
Stack trace:
#0 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Request.php(20): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(578): include('...')
#2 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}()
#3 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php(31): Composer\Autoload\ClassLoader->loadClass()
#4 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns/CreatesApplication.php(332): Illuminate\Foundation\Bootstrap\SetRequestForConsole->bootstrap()
#5 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns/CreatesApplication.php(223): Orchestra\Testbench\TestCase->resolveApplicationBootstrappers()
#6 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase.php(73): Orchestra\Testbench\TestCase->createApplication()
#7 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns/Testing.php(79): Orchestra\Testbench\TestCase->refreshApplication()
#8 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase.php(41): Orchestra\Testbench\TestCase->setUpTheTestEnvironment()
#9 /home/runner/work/baum/baum/tests/Baseline/UnitAbstract.php(14): Orchestra\Testbench\TestCase->setUp()
#10 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCase.php(1147): Baum\Tests\Baseline\UnitAbstract->setUp()
#11 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#12 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCase.php(904): PHPUnit\Framework\TestResult->run()
#13 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestCase->run()
#14 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run()
#15 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit\Framework\TestSuite->run()
#[16](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:17) /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite->run()
#[17](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:18) /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run()
#[18](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:19) /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run()
#[19](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:20) /home/runner/work/baum/baum/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#[20](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:21) /home/runner/work/baum/baum/vendor/bin/phpunit(123): include('...')
#[21](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:22) {main} in /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 20
..
In Request.php line 20:
                                                                               
  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of   
  Illuminate\Http\Request::offsetExists($offset) should either be compatible   
  with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWi  
  llChange] attribute should be used to temporarily suppress the notice in /h  
  ome/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http/Requ  
  est.php:637                                                                  
  Stack trace:                                                                 
  #0 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Http  
  /Request.php(20): Illuminate\Foundation\Bootstrap\HandleExceptions->handleE  
  rror()                                                                       
  #1 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(578): includ  
  e('...')                                                                     
  #2 /home/runner/work/baum/baum/vendor/composer/ClassLoader.php(432): Compos  
  er\Autoload\ClassLoader::Composer\Autoload\{closure}()                       
  #3 /home/runner/work/baum/baum/vendor/laravel/framework/src/Illuminate/Foun  
  dation/Bootstrap/SetRequestForConsole.php(31): Composer\Autoload\ClassLoade  
  r->loadClass()                                                               
  #4 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns  
  /CreatesApplication.php(332): Illuminate\Foundation\Bootstrap\SetRequestFor  
  Console->bootstrap()                                                         
  #5 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns  
  /CreatesApplication.php([22](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:23)3): Orchestra\Testbench\TestCase->resolveApplicat  
  ionBootstrappers()                                                           
  #6 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase  
  .php(73): Orchestra\Testbench\TestCase->createApplication()                  
  #7 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/Concerns  
  /Testing.php(79): Orchestra\Testbench\TestCase->refreshApplication()         
  #8 /home/runner/work/baum/baum/vendor/orchestra/testbench-core/src/TestCase  
  .php(41): Orchestra\Testbench\TestCase->setUpTheTestEnvironment()            
  #9 /home/runner/work/baum/baum/tests/Baseline/UnitAbstract.php(14): Orchest  
  ra\Testbench\TestCase->setUp()                                               
  #10 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCa  
  se.php(1147): Baum\Tests\Baseline\UnitAbstract->setUp()                      
  #11 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestRe  
  sult.php(728): PHPUnit\Framework\TestCase->runBare()                         
  #12 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestCa  
  se.php(904): PHPUnit\Framework\TestResult->run()                             
  #13 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSu  
  ite.php(675): PHPUnit\Framework\TestCase->run()                              
  #14 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSu  
  ite.php(675): PHPUnit\Framework\TestSuite->run()                             
  #15 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/Framework/TestSu  
  ite.php(675): PHPUnit\Framework\TestSuite->run()                             
  #16 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/TestRunne  
  r.php(653): PHPUnit\Framework\TestSuite->run()                               
  #17 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.p  
  hp(144): PHPUnit\TextUI\TestRunner->run()                                    
  #18 /home/runner/work/baum/baum/vendor/phpunit/phpunit/src/TextUI/Command.p  
  hp(97): PHPUnit\TextUI\Command->run()                                        
  #19 /home/runner/work/baum/baum/vendor/phpunit/phpunit/phpunit(98): PHPUnit  
  \TextUI\Command::main()                                                      
  #20 /home/runner/work/baum/baum/vendor/bin/phpunit(1[23](https://github.com/TopOnePercent/baum/actions/runs/3958461341/jobs/6780062824#step:7:24)): include('...')      
  #21 {main}

### PR DESCRIPTION
**Pull request by bkintanar**
Fixes: https://github.com/TopOnePercent/baum/issues/25

### CODE REVIEW

**Comment by foresight-developers** [comment]
@bkintanar under /.github/workflows/run_tests.yml can you add php 8.1 to the github actions test? so we can ensure everything checks out.

Change this:
`strategy:
      matrix:
        php: [8.0, 7.4, 7.3]`

To this:
`strategy:
      matrix:
        php: [8.1, 8.0, 7.4, 7.3]`

**Comment by bkintanar** [comment]
@foresight-developers done.

**Comment by bkintanar** [comment]
@foresight-developers i see warnings. but the pipeline is failing. I'm not sure why.

**Comment by foresight-developers** [comment]
@bkintanar we have it set where even warnings cause it to fail. We need to look into why we are getting those warnings. Depending on that answer we may add a comment to have the test ignore them. I think you are still fine to do the migration of the xml file to the new format, as that isnt the issue I believe.

**Comment by bkintanar** [comment]
@foresight-developers ok. I've restored the updated phpunit.xml

**Comment by foresight-developers** [comment]
@bkintanar we are looking into this issue over the next few days, unfortunately we cant dedicate someone to this full time currently, but we will let you know if we figure anything out. Again many thanks for supporting this project!

**Comment by foresight-developers** [comment]
@bkintanar we have yet to allocate much time to this however it is on our development road map within the next several months

**Comment by foresight-developers** [comment]
@bkintanar we will be looking at this in the coming weeks but if you want to try the following:

"You can rename the trait from NodeModelExtensionsTest to NodeModelExtensionsTestTrait.

Starting with PHPUnit 10, files in your configured test directory that end with a configured suffix (see testsuites>testsuite>directory) in phpunit.xml must be classes extending PHPUnit\Framework\TestCase.

I couldn't find an explanation for why it was changed unfortunately. A related issue on GitHub for some context: https://github.com/sebastianbergmann/phpunit/issues/4979."

**Comment by foresight-developers** [comment]
@bkintanar looks like that has done the trick, the warning is not an issue so we will have to put something in place to ignore it, most likely in the github actions

**Comment by foresight-developers** [comment]
@bkintanar in the phpunit.xml if we remove the lines that auto generate the report coverage.txt then the warning most likely will go away, we dont really need to run a coverage report everytime we run phpunit anyways.

**Comment by foresight-developers** [comment]
@bkintanar do you need assistance with that phpunit.xml edit? thanks

**Comment by bkintanar** [comment]
@foresight-developers updated. sorry to take so long. can this be merged now?

**Comment by foresight-developers** [comment]
@bkintanar we are reviewing the code right now, if everything checks out we can merge.

**Comment by bkintanar** [comment]
Thanks! Can we tag a release version too please?

**Comment by foresight-developers** [comment]
@bkintanar I need to add to the readme the newly supported php version etc, this also supports laravel 10 right? so https://github.com/TopOnePercent/baum/pull/31 can be closed?

**Comment by foresight-developers** [comment]
@bkintanar Thanks for all the help here it is: https://github.com/TopOnePercent/baum/releases/tag/3.1.0 We're based in the U.K, but I will be back online 6 hours if you need anything else.

**Pull request merged**
